{% set data = load_setup_py_data() %}

package:
  name: nonpher
  version: {{ data.get('version') }}

build:
  noarch: python
#  always_include_files:
#    - bin/nonpher.sh
  preserve_egg_dir: True

extra:
  channels:
    - rdkit
    - lich

source:
  path: ../
#  git_rev: latest
#  git_url: file:///home/milan/workspace/nonpher

requirements:
  build:
      - python
      - setuptools


  run:
      - python
      # - rdkit due to some issue in requirments in molpher-lib, versions of molpher-lib, rdkit and libboost are fixed
      - molpher-lib =0.0.0b2
      - rdkit =2018.03.1
      - libboost =1.65

# test:
#  imports:
#    - nonpher

about:
  home: https://github.com/lich-uct/nonpher
  license: GPL-3.0
  license_file: LICENSE
  summary: "Software library for designing hard-to-synthesize structures"
